### PR TITLE
Changes abstract into a variable and separates template, content, for…

### PR DESCRIPTION
**Pull request by mturilli**
…matting

Fairly invasive pr:
- Create a landing page only for publications that have an abstract
- Make formatting of landing page uniform across publications
- Add paper and/or abstract links  to the publication lists only when they are available
- Change formatting of both publication list and landing pages

For posterity, here the regex I used to convert abstract into a variable on the landing pages:
```
(?s)^\-+([\n]{2}|\n\[)(\#+ Abstract[\:\t ]*)?(?(2)\n+(((?!(\n){2}).)*+).+|.+)
abstract: "$3"\n---\n
```

### CODE REVIEW

**Review by iparask — CHANGES_REQUESTED** [review]
This is actually pretty invasive PR. It looks nice and it might make sense to have the abstract as part of the header.

But having in the landing page the links on the side although it helps a bit in browsers, it is very diffucult to navigate on remote devices.

That is the case for wrapping the abstract text around the paper url.

I am attaching a couple of pictures of how this would look like on an iPhone 6:

image

image

**Comment by iparask** [comment]
May I suggest that we bring those 2 links next to the venue?

**Comment by mturilli** [comment]
Thanks, had forgotten to check how it looks on a mobile. Better?

**Review by iparask — APPROVED** [review]

**Comment by iparask** [comment]
It definitely looks better! Thank you!

**Pull request merged**
