### PR TITLE
Home page redesign

### PR DESCRIPTION
**Pull request by mturilli**
The redesign is ongoing (i.e., not mobile friendly yet). Help is welcome :)

### CODE REVIEW

**Comment by iparask** [comment]
These are my 2 cents. I find it very compressed and a bit much information in small space. For example, having the picture of the lab with the address and the twitter feed right next to it, it makes it difficult for me to read the page.

Why not have two columns below the figure with the feed and the blog and after it two more columns with the research and the development?

Still though, I prefer pages that offer me the necessary information and nothing more. I prefer to navigate to different parts of the page as to having everything in the home page..

**Comment by mturilli** [comment]
Thanks for the feedback. We can play with the design of the homepage but maybe we should agree before on what to put there? As previously agreed, the photo will go so I should probably take it off already from the new page. What information do you think we should put on the home page? As the 'about' page has to go too, my suggestion is to reduce the text under 'Research' and use it as opening of the publications page; and do the same with 'Software Development' with the projects page. Alternatively, we can put the text in the home page, a solution that I may prefer.

**Comment by mturilli** [comment]
Better?

**Comment by iparask** [comment]
This is amazing! It looks way better than before! I agree with your suggestions. In addition, I think that part of the research text can also be in the projects opening page. It's up to you, you're doing an amazing job with how the page looks.
Do you want to remove the Twitter feed completely? I thought that was our news feed.

**Comment by mturilli** [comment]
Great, glad we are on the right path. About the twitter feed, I did not find a good way to integrate it into the home. I put the twitter link in evidence, I think it should be enough. Would you agree? OK for the research text. If you agree, I will give it another go and then I think we should be ready to merge.

**Comment by iparask** [comment]
Yes, I agree

**Review by iparask — APPROVED** [review]

**Pull request merged**
