### PR TITLE
Suggestion for publications formatting

### PR DESCRIPTION
**Pull request by mturilli**
This offers a more canonical formatting of publication entries limiting the link to the abstract to the title of the paper. We may want to consider a double link at the end of the entry with [Paper URL] and [Abstract URL].

### CODE REVIEW

**Review by iparask — COMMENTED** [review]
In my opinion it is a bit weird for the link not to be at the beginning of the entry. If we agree with the title being a link to the abstract, then would a <Title,Authors,Venue,[PaperLink]> format be better?

**Comment by andre-merzky** [comment]
I don't have a problem with the link not being in the beginning of the entry.  We had something similar on the old page (which means that I am biased ;-) )

**Comment by mturilli** [comment]
Would something like this work better?

### Publications

#### 2018

- Ioannis Paraskevakos, Andre Luckow, Mahzad Khoshlessan, George Chantzialexiou, Thomas E. Cheatham, Oliver Beckstein, Geoffrey C. Fox and Shantenu Jha. Task-parallel Analysis of Molecular Dynamics Trajectories, 47th International Conference on Parallel Processing (ICPP 2018).
[Abstract] [Paper]

**Comment by vivek-bala** [comment]
Since this is a discussion about the style, I would like to make the following suggestions
regarding readability:

* Can we lead the entry with the title of the paper? Anyone viewing the website would be
interested in the title of the paper. The viewer should not have to "search" for the title 
after a long list of authors. (this is the current style on the website)

* Separate the title with change in font style? For simplicity, title in bold?

* Can we hide the "bullet" and show separation between two publications by linebreaks?
Both the circle of the bullet and the indentation don't look nice on website.

* Since suggestion 1 is to remove the bib style entry, we may want to consider providing
the bib entry via a URL.

Example:

## Publications

### 2018

**Task-parallel Analysis of Molecular Dynamics Trajectories, 47th International Conference on Parallel Processing**
Ioannis Paraskevakos, Andre Luckow, Mahzad Khoshlessan, George Chantzialexiou, Thomas E. Cheatham, Oliver Beckstein, Geoffrey C. Fox and Shantenu Jha 
47th International Conference on Parallel Processing (ICPP 2018)
[Abstract] [Paper] [Bib]

**Harnessing the Power of Many: Extensible Toolkit for Scalable Ensemble Applications**
Balasubramanian, Vivek, Matteo Turilli, Weiming Hu, Matthieu Lefebvre, Wenjie Lei, Guido Cervone, Jeroen Tromp and Shantenu Jha
32nd IEEE International Parallel and Distributed Processing Symposium
[Abstract] [Paper] [Bib]

**Comment by mturilli** [comment]
I am not sure I agree with the assumption that viewers of the page will want to see the title of the paper first. For me, this is equivalent to a bibliographic entry and in all the styles I have ever seen, either on papers or CVs, the canonical format starts with the author list. The same reasoning would apply to separating the elements of an entry with a line break. Searching for 'research group publications' seems to support this interpretation.

I would not have a problem with:
- a bold face for the title;
- three links after a line break; and
- no list for each entry.

**Comment by andre-merzky** [comment]
I agree with Vivek on this one, and would also prefer to put the title first.  But that's not a strong preference: the title being bold is more important.  I also like the link to the bib-entries: I myself find this useful on other peoples' pages when I see it.

**Comment by iparask** [comment]
I do not have any preference in what will be first and what not. I agree that having the link to go to the abstract is nice. 

I do not like bibentries as links and any bib file existing in this repo. First of all, it will create a mess with different bib entry styles. Second, the paper link should point to the actual link of where the paper is published. All vendors provide bibliography entries. That is valid also for paper links that point to Arxiv. they should not in any way link directly to the PDF.

In addition to all that. I think that the name in the author list should always be <First Last> separated with commas between authors and the last with and - no oxford commas here please.

**Comment by vivek-bala** [comment]
I agree that on a paper and CV it is recommended to have it as a bib entry. But on a website, I would expect/prefer the publication list to be of the style we have on research gate or google scholar or linkedin: title first.

I agree with your point that most viewers will be accustomed to bib-style entries. I think we have more flexibility when it comes to the website and can explore this idea: Take the viewer's attention (quickly) to 'what the publication is about' rather 'who wrote the publication' (viewer already knows it is by someone from the group). 

I understand style preference is subjective, just wanted to share the reasoning behind my suggestion.

**Comment by mturilli** [comment]
Thanks for the feedback. Would this be a good compromise for everyone?
screen shot 2018-10-10 at 10 15 52 am

**Comment by vivek-bala** [comment]
Yes, works for me.

**Review by andre-merzky — APPROVED** [review]
Thanks!

**Review by iparask — APPROVED** [review]

**Review by vivek-bala — APPROVED** [review]

**Comment by shantenujha** [comment]
I don't have a strong preference, but I think title of the paper as boldface is easier on the eye, than italicized.

**Review by shantenujha — COMMENTED** [review]
Yes, good to go. As accidentally said elsewhere, "I don't have a strong preference on style, but all else being equal, I think the title in boldface is easier on the eye, than italicized".

**Pull request merged**
