### PR TITLE
Reduced HTBAC txt to single paragraph

### PR DESCRIPTION
**Pull request by jdakka**

### CODE REVIEW

**Review by mturilli — CHANGES_REQUESTED** [review]
Please see my comment about link to project vs link to call for proposals. Once this has been addressed, I think we will be ready to merge.

**Comment by iparask** [comment]
This PR will close #32

**Comment by jdakka** [comment]
I looked for the award number as well but I was not able to find it, that's why I added the call instead. @shantenujha can you refer a link for the prac award with UCL?

**Comment by shantenujha** [comment]
https://www.nsf.gov/awardsearch/showAward?AWD_ID=1713749&HistoricalAwards=false

(Just FYI, I believe this link was provided on previous website, and thus note to us all to not remove without proper / careful archiving)

**Comment by jdakka** [comment]
Added link

**Review by mturilli — APPROVED** [review]

**Pull request merged**
