### PR TITLE
Feature/twitter

### LINKED ISSUE #54: Create a RADICAL Lab twitter account
How do we call it?

### PR DESCRIPTION
**Pull request by iparask**
Adding Twitter handle, changing news to blog.

The new homepage features a Twitter stream after the contact information. This will automatically update with our tweets! We can add more.

The news page became a blog and went to the end of the list. The homepage will also feature the latest blog entries after the twitter handle.

Fixes #54

### CODE REVIEW

**Comment by mturilli** [comment]
I get the following error when trying this locally with `jekyll serve`:
```
  Liquid Exception: Liquid error (line 1): Cannot sort a null object. in blog.md
             Error: Liquid error (line 1): Cannot sort a null object.
             Error: Run jekyll build --trace for more information.
```
When I try it with `jekyll build --trace` everything works...

**Comment by iparask** [comment]
The error you are seeing is coming from line 6 of `blogs.md` where things get sorted. It seems like it does not find any `_blog` folder to sort. The `_news` folder is renamed to `_blog`.  Can you check that all these hold.

Also make sure that the `_site` folder is deleted. This is the compiled site and I am not sure if it leaves anything behind when the site gets recompiled.

**Comment by mturilli** [comment]
Thanks, that did the trick. Once we converge on headings, we should probably have a first pass at formatting the hoe page. At the moment, the font of the twitter feed is huge and the headings are small. What do you think?

**Comment by iparask** [comment]
I made the widget a bit smaller. Can you please check? I definitely agree with you!

**Comment by mturilli** [comment]
I started to iterate on the scss of the site but it is proving to be a fairly long endeavor. Should we merge as it is and then focus on the styles?

**Comment by iparask** [comment]
Yes, since that will bring it closer to what we want. Also it brings twitter and closes the news ticket. The style of the widget may not be perfect, but we have functionality and we may get some followers. Right now only AndreL is following our Twitter

**Review by mturilli — APPROVED** [review]
Ready to go :)

**Pull request merged**
