### PR TITLE
Iterate publications and fix html errors

### PR DESCRIPTION
**Pull request by mturilli**
- Makes formatting consistent across the page
- Fixes errors with lists (and maybe with paragraphs)
- Eliminates empty Venue variable
- Eliminates drafts

### CODE REVIEW

**Review by iparask — COMMENTED** [review]
The publications that had draft in their type remained us such until we update them, right? I think it is okay. Let me correct the conflicts and I will approve it.

**Comment by mturilli** [comment]
Following our previous discussion, I think we agreed not to have drafts on the website at all. The idea is to have only publications on: arXiv.org, proceedings, journal. For proceedings and journals, we will probably end up having 'accepted for publication' and then, once they are published, 'page' and 'volume'. As agreed, it will be a challenge to keep these in synch but, at the moment, I do not see a way to automate it.

**Comment by iparask** [comment]
I definitely agree with you here! I will find them and make the required changes in a fix branch. I fix the conflict here and removed one of Shantenu's duplicate publication. As soon as Travis finishes, I will merge.

**Comment by iparask** [comment]
I still do not understand why Travis fails. Should we pay attention or it is still in the works?

**Review by iparask — APPROVED** [review]

**Comment by mturilli** [comment]
Yes, we should pay attention to Travis. Part of this pr is indeed to address some of the errors that makes html-proof fail the build. Please feel free to merge.

**Pull request merged**
